#!/bin/bash

###
### SIGPI
###
### cfg_simple-ax25
###

CALLSIGN = $2
SSID = "-1"
STATION = "$CALLSIGN$SSID"

echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##  Configure Simple AX25"
echo -e "${SIGPI_BANNER_RESET}"

sudo mv /etc/rc.local /etc/org.rc.local
sudo cp $SIGPI_SCRIPTS/simple-ax25.rc.local /etc/rc.local

echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##   Simple AX25 Configured"
echo -e "${SIGPI_BANNER_RESET}"