#!/bin/bash

###
### SIGPI
###
### cfg_simple-ax25
###

echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##  Install Simple AX25 Startup"
echo -e "${SIGPI_BANNER_RESET}"

sudo mv /etc/rc.local /etc/org.rc.local
sudo cp $SIGPI_SCRIPTS/simple-ax25.rc.local /etc/rc.local

echo -e "${SIGPI_BANNER_COLOR}"
echo -e "${SIGPI_BANNER_COLOR} ##  Simple AX25 Startup Installed"
echo -e "${SIGPI_BANNER_RESET}"